version: "3.9"

services:
  add-service:
    build:
      context: .
      dockerfile: Calc_Service_Add/Dockerfile
    depends_on:
      - rabbitmq
      - seq
    restart: on-failure
    deploy:
      replicas: 3
  web-service:
    build:
      context: .
      dockerfile: CalculatorFrontend/Dockerfile
    depends_on:
      - calc-service
    restart: on-failure
    ports:
      - 8080:80
  sub-service:
    build:
      context: .
      dockerfile: Calc_Service_SubTract/Dockerfile
    depends_on:
      - rabbitmq
      - seq
    restart: on-failure
    deploy:
      replicas: 3
  calc-service:
    build:
      context: .
      dockerfile: Calc_Service_API/Dockerfile
    depends_on:
      - add-service
      - sub-service
      - rabbitmq
      - seq
    restart: on-failure
    ports:
      - 8082:80    
  rabbitmq:
    hostname: rabbitmq
    labels:
      - NAME=rabbitmq
    image: rabbitmq:3-management
    ports:
    - "15672:15672"
  seq:
    image: datalust/seq
    hostname: seq
    labels:
      - NAME=seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
  zipkin:
    image: openzipkin/zipkin
    hostname: zipkin
    labels:
      - NAME=zipkin
    ports:
      - 9411:9411
volumes:
  rps_seq_data: